name: ParaToGit

on:
  workflow_dispatch:
  schedule:
    - cron: '0 16 * * *'  # 每天UTC时间16点运行

jobs:
  sync:
    runs-on: windows-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r .github/requirements.txt

      - name: Run sync script
        id: sync_terms
        shell: pwsh
        env:
          PARATRANZ_API_KEY: ${{ secrets.PARATRANZ_API_KEY }}
          PROJECT_ID: 13798
        run: |
          python .github/scripts/sync_terms.py
          $run_time = Get-Date -Format "yyyy-MM-dd HH:mm:ss"
          $has_error = if ($LASTEXITCODE -ne 0) { "true" } else { "false" }
          echo "run_time=$run_time" | Out-File -FilePath $env:GITHUB_OUTPUT -Encoding utf8 -Append
          echo "has_error=$has_error" | Out-File -FilePath $env:GITHUB_OUTPUT -Encoding utf8 -Append

      - name: Commit changes
        if: steps.sync_terms.outputs.has_error == 'false'
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add terms-13798.json
          git commit -m "Update terms from ParaTranz [skip ci]"
          git push

      - name: Upload error logs
        if: steps.sync_terms.outputs.has_error == 'true'
        uses: actions/upload-artifact@v4
        with:
          name: error-logs
          path: |
            .github/logs/*.log
            terms-13798.json
